packages:
  - packages/*

catalog:
  "@types/node": ^22
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
