name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  vite:
    name: Vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: voidzero-dev/setup-vp@143f5f385f39b1b753ffed1a01ad443811855c8b # v1.16.1
        with:
          cache: true

      - run: vp install
      - run: vp run -r generate
      - run: vp run -r build
      - run: vp check
      - run: vp run -r test

      - name: Upload to SCA Tool
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: node packages/cli/dist/cli.mjs revisions create-sbom main --codebase .
        env:
          SCATOOL_TOKEN: ${{ secrets.SCATOOL_TOKEN }}
          SCATOOL_PROJECT_ID: ${{ secrets.SCATOOL_PROJECT_ID }}
